### ISSUE TITLE
every first/second/fourth/last monday every two months

### ISSUE THREAD

**Issue by rockschtar** [c-trimm/moment-recur#10]
Can I do this with recur:

"every first/second/fourth/last monday every two months"?

**Comment by bramski** [comment]
This repository seems to be defunct but this plugin is very useful.  Since @c-trimm has not touched it in 6 months I have made some updates and moved it to: https://github.com/bramski/moment-recur-js

Please revisit your issue there, thanks!

**Comment by c-trimm** [comment]
Currently, moment-recur does not support the ability to specify the n-th weekday of a month.
