### ISSUE TITLE
storing and quering

### ISSUE THREAD

**Issue by lukasa1993** [c-trimm/moment-recur#11]
i saw in docs .save() function i understand thats the way to store but, to use only that then i cant do query in db side i would require to grab them all put in js and the do query so can you suggest anything?

**Comment by bramski** [comment]
This repository seems to be defunct but this plugin is very useful.  Since @c-trimm has not touched it in 6 months I have made some updates and moved it to: https://github.com/bramski/moment-recur-js

Please revisit your issue there, thanks!

**Comment by c-trimm** [comment]
@lukasa1993 .save() just returns an object with the rules, exceptions, start and end dates. You could split that up as needed to store in a database. I really depends on your specific use case.

**Comment by c-trimm** [comment]
Question hasn't been addressed for 2 months. Closing.
