### ISSUE TITLE
Minified Version In Bower Package

### ISSUE THREAD

**Issue by Dacke** [c-trimm/moment-recur#13]
Can you please include a minified version in the bower package as well as the expanded version

**Comment by bramski** [comment]
This repository seems to be defunct but this plugin is very useful.  Since @c-trimm has not touched it in 6 months I have made some updates and moved it to: https://github.com/bramski/moment-recur-js

Please revisit your issue there, thanks!

This specific issue is fixed there.

**Comment by bramski** [comment]
Please see: https://github.com/c-trimm/moment-recur/releases/tag/v1.0.1
