### ISSUE TITLE
Depends on 2.4.0 version of moment.js

### ISSUE THREAD

**Issue by Dacke** [c-trimm/moment-recur#14]
Currently the version in the bower package relies on version 2.4.0 of moment.js but they are up to 2.8.4.  Can this be fixed?

**Comment by bramski** [comment]
This repository seems to be defunct but this plugin is very useful.  Since @c-trimm has not touched it in 6 months I have made some updates and moved it to: https://github.com/bramski/moment-recur-js

Please revisit your issue there, thanks!

This specific issue is fixed there.

**Comment by bramski** [comment]
Please see: https://github.com/c-trimm/moment-recur/releases/tag/v1.0.1
