### ISSUE TITLE
Need ability to get number of intervals including start date

### ISSUE THREAD

**Issue by bronsquire** [c-trimm/moment-recur#22]
Love this library, thank you!
I have a case (which I'm not sure would be overly specific to me), where I need to be able to set a start date for an interval, setup necessary recurrence and then get the "next x" dates.  I don't want to specify the end date (though we do take this value from the user, but it could be wrong, and the number of dates is always "correct").
For simplicity, let's say I want to do a weekly recurrence (in truth I can do weekly, fortnightly or monthly).

```
var startDate = "2015-02-25";
var intervals = moment(startDate).recur().every(1).week();
intervals.except(self.tournament().params.DatesNotPlayed());
````

I then run the following and store the resulting array somewhere for use later:

```
var allDates = intervals.next(numberOfRounds);
```

The result will be x dates where x is `numberOfRounds`.  It DOESN'T include the start date, though, and I want it to.

I've tried using the .all() function but of course then I can't control how many dates I get, and if I use a user-defined "end" date, it may not end up in enough dates being generated.

A spanner in the works (I just realised I'm not doing this yet!) is that I still have to also implement it including the "day of week" to recur on, so e.g. every Wednesday weekly, every Wednesday fortnightly, or every Wednesday monthly.  I'm imagining i would do this by first manipulating my start date to be the next Wednesday (or whatever day) after the given start date inclusive.

Is there any way of doing what I need to do now, or if not do you have any reason for it not being there? I can try to come up with a solution for it if you like, if you'd like to see it in there.

**Comment by bramski** [comment]
Hey @bronsquire , would not using .next(n-1) and adding the start do for you?

https://github.com/c-trimm/moment-recur#generating-dates
```
dates = _.union([intervals.start], intervals.next(numberOfRounds-1));
```

**Comment by bronsquire** [comment]
Thanks for your quick response and suggestion!  I ended up doing a similar thing (though I happened to use next(n-1) followed by an unshift to add the first date to the start).  Might look at the benefits of using union rather than unsift (especially to bring it into one line!)
