### ISSUE TITLE
suggestion for new features

### ISSUE THREAD

**Issue by timcullen** [c-trimm/moment-recur#23]
Great job, Casey.  This is just what Ive been looking for.  Would it be possible to add new methods such as 

1 count(start,end) would return the number of occurrences within the given range
2 last() would give the last occurrence (only available when end date is specified)
3 get(start,end) would return an array containing all occurrences within the given period. I suppose this could be done already by specifying a from and end date and using the all() method?

one final thought.  is it possible to turn off the console.logging of all Match results?

**Comment by timcullen** [comment]
I notice that the version available on NPM (1.0.0) seems to be older than the latest version on Git? The latest version seems to have turned off the console logging of matches (good!) and also adds the new recurrence.all() method which wasn't working for me.  Would it be possible to upload the latest version to NPM ?

**Comment by c-trimm** [comment]
Hey @timcullen, thanks for your feedback. I'll look into add those new features some time, they shouldn't be too terribly hard to implement.

NPM has also been updated to reflect the latest release of moment-recur. Sorry for any inconvenience it may have caused.

Let me know if you have any questions or if I can be of any further assistance.

Thanks.
