### ISSUE TITLE
When to update the 1.0.4 version to the npm?

### ISSUE THREAD

**Issue by gko1943** [c-trimm/moment-recur#24]
When to update the 1.0.4 version to the npm?

**Comment by gko1943** [comment]
The 1.0.0 version's "console.log" break my unittest

**Comment by mocheng** [comment]
+1

https://github.com/c-trimm/moment-recur/blob/v1.0.0/moment-recur.js#L265

Our CI system generates XML for report. The 'console.log' in v1.0.0 breaks the XML structure and make it fail.

It would be lovely to have a officual npm release without the "console.log".

**Comment by wuxiaoxiong** [comment]
+1 

looking forward to this update too.

**Comment by 119786155** [comment]
Unit testing does not allowed console.log

**Comment by rambo-panda** [comment]
+1 @gko1943

**Comment by xieziosky** [comment]
+1

**Comment by c-trimm** [comment]
moment-recur has been updated to 1.0.4 on NPM. Sorry for any inconvenience this may have caused, and thank you for your patience.

Please let me know if there are any further questions or if I can be of assistance in any way.

Thanks.
