### ISSUE TITLE
Clone

### ISSUE THREAD

**Issue by gso** [c-trimm/moment-recur#29]
Method (literally or otherwise) to clone a moment recur object.

**Comment by c-trimm** [comment]
You could use the .save() function, which generates an options object that can be fed back into a new recurrence.

**Comment by gso** [comment]
The project was EonJS https://bitbucket.org/gso/eonjs/src

Not sure off the top of my head why this arose, possibly some sort of edit 'undo' feature.  If I wake the project up again the problem looks solved.

Cheers,
