### ISSUE TITLE
Support ISO8601 recurring date parsing

### ISSUE THREAD

**Issue by stevage** [c-trimm/moment-recur#30]
It seems remiss not to support parsing ISO8601 recurring intervals like `R/2015-01-14/P2W`.

**Comment by bramski** [comment]
Is this something you need?  Can't say I'm certain if moment-recur supports all of the recurrences possible in ISO8601.

**Comment by stevage** [comment]
Here's the context: http://stackoverflow.com/questions/29457872/do-any-javascript-libraries-support-iso8601-recurring-intervals

I probably don't "need" it, but if there had been support for it, I'd be using it.

**Comment by bramski** [comment]
Okay.  Feel free to write a PR.  I have no uses for this functionality.
