### ISSUE TITLE
moment .add method deprecated

### ISSUE THREAD

**Issue by gso** [c-trimm/moment-recur#31]
I'm not sure exactly which moment-recur method gives this warning, however:

    Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period). 

The JS specifically, `example.html` https://bitbucket.org/gso/eonjs/

**Comment by Maximization** [comment]
This has been solved in 36d0e417a2eb0d8ce6f4bff4be0572a9c281cfc3. Strangely enough bower install or update (even with -f) doesn't install from current master. Perhaps a version bump will solve?

**Comment by bramski** [comment]
I've made a new release (v1.0.5).  Should fix this for you.

**Comment by Maximization** [comment]
Great, thanks!

**Comment by gso** [comment]
I think the new version will need to be published to npm also, still stuck on 1.0.4.

**Comment by c-trimm** [comment]
Published. Thanks, gso.
