### ISSUE TITLE
Deprecation warning: months accessor is deprecated. Use month instead

### ISSUE THREAD

**Issue by ozum** [c-trimm/moment-recur#33]
Hello,

The code below from examples produces "Deprecation warning: months accessor is deprecated. Use month instead."

    var valentines = moment().recur("2014-01-01", "2014-05-05").
        every(14).daysOfMonth().every("Februray").monthsOfYear();
        console.log(util.inspect(valentines.next(3, 'L')));

Best Regards,

**Comment by ehacke** [comment]
I patched this on my branch. Here's the pull request: https://github.com/c-trimm/moment-recur/pull/38
