### ISSUE TITLE
Support for hours, minutes, seconds

### ISSUE THREAD

**Issue by ghost** [c-trimm/moment-recur#39]
May I know why time is not supported? As I would like to do:

`var recurrence = moment().recur("01/01/2014", "01/07/2014").every(15).minutes();`

I would like to contribute if necessary. Thank you.

**Comment by bramski** [comment]
Because nobody has written such support.  This may be very complex to support in this library though given it is strongly tied to date only recurrences.

**Comment by dohomi** [comment]
Hey guys, 
would like to know if any knows if `recur` could support time of day somehow. I would like to repeat over days but in specific time. Like: `every Monday 7:00 PM`. 
Cheers Dominic

**Comment by c-trimm** [comment]
There are no plans for this library to support times. If someone would like to write such support, I wouldn't be opposed to it, but as bramski said, it's strongly tied to dates.
