### ISSUE TITLE
Interval 1 Month on Month with 29-31 days overjump month with lower days...

### ISSUE THREAD

**Issue by Dexus** [c-trimm/moment-recur#4]
Hi,

there is an failure in the interval...

if i have a start date i.e. 2014-01-31 and an interval of 1 month
the next date is the 2014-03-31 so its not 1 month as except... its 2 month interval...

the correct interval must return the last day of the month if the next month will have a lower count of days...

**Comment by bramski** [comment]
This repository seems to be defunct but this plugin is very useful.  Since @c-trimm has not touched it in 6 months I have made some updates and moved it to: https://github.com/bramski/moment-recur-js

Please revisit your issue there, thanks!
