### ISSUE TITLE
.next returns wrong dates

### ISSUE THREAD

**Issue by CorasApps** [c-trimm/moment-recur#43]
From the README.md I used this example:

// Create a recurrence
recurrence = moment("01/01/2014").recur().every(2).days();

// Generate the next three dates as moments
// Outputs: [moment("01/03/2014"), moment("01/05/2014"), moment("01/07/2014")]
nextDates = recurrence.next(3); 

My outputs are:
// Outputs: [moment("01/02/2014"), moment("01/04/2014"), moment("01/06/2014")]

**Comment by bholbrook73** [comment]
This is likely a timezone issue. I'm betting that moment.utc("01/01/2014").recur().... will do what you need. You can also do moment.recur("01/01/2014").... which sets the start date.

**Comment by CorasWorksSolutions** [comment]
@bholbrook73 Both suggestions yield the same result as I reported in the original post.

**Comment by c-trimm** [comment]
Seems to work as expected here: https://jsfiddle.net/gg9gtm0c/
If you are still around and have any more information regarding the issue (actual source code would help), please let me know. Thanks.

**Comment by garaboncias** [comment]
As bholbrook73 suggested this is locale issue, but this is a bug in moment-recur
because moment-recur use moment.dateOnly() which is not documented (deprecated?) and not locale aware
I suggest lib should use moment.startOf('day')
```
moment("01/02/2017","MM/DD/YYYY").utcOffset(120,true).toString()
"Mon Jan 02 2017 00:00:00 GMT+0200"
moment("01/02/2017","MM/DD/YYYY").utcOffset(120,true).recur().every(1).daysOfWeek().next(1)[0].toString()
"Mon Jan 02 2017 22:00:00 GMT+0000"
moment("01/02/2017","MM/DD/YYYY").utcOffset(0,true).toString()
"Mon Jan 02 2017 00:00:00 GMT+0000"
moment("01/02/2017","MM/DD/YYYY").utcOffset(0,true).recur().every(1).daysOfWeek().next(1)[0].toString()
"Mon Jan 09 2017 00:00:00 GMT+0000"
```

**Comment by YaoHuiJi** [comment]
It should be nice to add a note to document to tell users that moment-recur will return  moment objects in UTC mode.
