### ISSUE TITLE
Date format output

### ISSUE THREAD

**Issue by jrgd** [c-trimm/moment-recur#51]
Moments is deprecating MM/DD/YYYY and other formats; details: [https://github.com/moment/moment/issues/1407](https://github.com/moment/moment/issues/1407)

When passing the result of next dates occurence from .recur() moment-recur outputs date in MM/DD/YYYY which when passed back to moments is triggering the Date deprecation warning 

`Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
`

The code I'm using to generate the next date array
```
var interval = moment.recur({
		start: start_date,
	    end: end_date
	}).every( recurring_frequency ).days();
var nextdates = interval.fromDate( today_date ).next(1,"L");
```

then this is what triggers the warning
`console.log( moment(nextdates[0]).format('YYYY-MM-DD') );
`

**Comment by c-trimm** [comment]
Use a format other than "L" - you can output the dates in any format you want.
