### ISSUE TITLE
.recur(string) and toISOString

### ISSUE THREAD

**Issue by saikatguha** [c-trimm/moment-recur#55]
ISO 8601 defines the string representation for Repeating Intervals. 
See https://en.wikipedia.org/wiki/ISO_8601

It would be super useful to be able to create a recurrence using:
`moment.recur(isoString)`

and to serialize it back as 
`moment.recur(...).toISOString()`

e.g.,

`moment().recur().every(1).days().toISOString() => "R/2016-08-21/P1D"`

**Comment by c-trimm** [comment]
I don't have a use for this, but feel free to implement it and create a PR.
