### ISSUE TITLE
Find events for specific day / timeframe

### ISSUE THREAD

**Issue by davidfloegel** [c-trimm/moment-recur#56]
Hi,

Great library!

I was wondering how a use case like this could be realised:

Say you have an event that is happening weekly. Now you want to view a specific day (in a calendar day view maybe) and see which events are happening on that day. 

Or you want to list all events happening in the future. 

As a dirty fix for now I fetch all events, generate the occurrences and then filter down. This works with a few events in a databse but obviously not with more. 

Any ideas on that?

David

**Comment by c-trimm** [comment]
Hi David,

You could try generating, say, a year's worth of dates for each event, save those to the database, and then pull from your database based on those dates. Perhaps a table with a date column and an event_id column, indexed by date would be relatively fast. Hope that helps!
