### ISSUE TITLE
moment deprecation warning possibly originating from moment-recur

### ISSUE THREAD

**Issue by ccuilla** [c-trimm/moment-recur#57]
I'm not 100% sure, but, I believe this line (moment-recur.js:737):

`return moment.tz(this.format('YYYY-MM-DD'), 'UTC');
`

Is causing this warning:

> Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.

I think you want to do this:

`return moment.tz(this.format('YYYY-MM-DDT00:00:00.000Z'), 'UTC');`

or

`return moment.tz(this.format('YYYY-MM-DD'), 'YYYY-MM-DD');`

**Comment by workdoer** [comment]
Fix this please... Who can do it?

**Comment by niftylettuce** [comment]
I will award a bug bounty to whomever updates this package with latest dependencies, latest version of moment, fixed tests, etc.

**Comment by niftylettuce** [comment]
I submitted a PR - if someone wants to avoid this issue until PR is accepted, `npm install --save niftylettuce/moment-recur`.

**Comment by niftylettuce** [comment]
@c-trimm can you publish a new version to NPM?

**Comment by c-trimm** [comment]
@niftylettuce done. Thanks for the contribution.
