### ISSUE TITLE
Not generating dates for 2017 (Next year of current date)

### ISSUE THREAD

**Issue by tahaerden** [c-trimm/moment-recur#58]
Hello, I have just started using this awesome plugin to generate some date lists with specific rules. 
I am not sure whether I am doing something wrong or it is a bug.
So my problem is as follows:

`var recurrence;
recurrence = moment("2015-01-01").recur("2016-01-01").every(1, "months");
allDates = recurrence.all("YYYY-MM-DD");
console.log(allDates);`

This returns the expected results (array length is 13).
But if I changed the start and end dates to: "2016-01-01" and "2017-01-01" the returning array is empty.

I also tried other notations and Options method along with days/weeks/months/years. Same result. 
So we cannot calculate the dates for next year?
Or is it caused by something else? Maybe the date format? I used this format because the MM/DD/YYYY format in the examples are giving a deprecation warning.

Thanks in advance!

**Comment by c-trimm** [comment]
Not sure if you're still around, but I attempted to recreate this bug, but could not:
https://jsfiddle.net/hmjfzhtf/

Everything seems to be working as expected. If you are still around and have any more information, please let me know. Thanks!
