### ISSUE TITLE
Question / feature request: missing some recurrence options

### ISSUE THREAD

**Issue by willemx** [c-trimm/moment-recur#6]
I like this lib very much!
...but, I also would like to set recurring events for:
- Last day of the month (payday!)
- 2nd monday in may (spring fair in our little village)
- Easter monday (or Pentecost, Ascension day, other special days...)
- offsets, like: 2 days before the last day of the month (could do Pentecost this way: 6 weeks after Easter)

or maybe some of these can be done already but I haven't found out how ?

**Comment by bramski** [comment]
This repository seems to be defunct but this plugin is very useful.  Since @c-trimm has not touched it in 6 months I have made some updates and moved it to: https://github.com/bramski/moment-recur-js

Please revisit your issue there, thanks!

**Comment by c-trimm** [comment]
Right now moment-recur only support simple rules for matching dates, but I'll see what I can do about adding in more advanced functionality for these types of dates. Thank you for your interest.
