### ISSUE TITLE
Bower install moment-recur#1.0.5 provides old code

### ISSUE THREAD

**Issue by MartijnWelker** [c-trimm/moment-recur#60]
In the current (latest) version the `moment.tz` call in `dateOnly` is like this (which is correct)

```
    return moment.tz(this.format('YYYY-MM-DD'), 'UTC');
```

However, when you bower install you get an old version

```
    return moment.tz(this.format("YYYY/MM/DD"), "UTC");
```

which will throw a deprecation warning

**Comment by c-trimm** [comment]
Bumped the bower config version - this should work correctly now.
