### ISSUE TITLE
Is it possible to set maximum count of repeats?

### ISSUE THREAD

**Issue by pie6k** [c-trimm/moment-recur#63]
Let's say I have rule that says:

Every 20th day of the month that is Monday and I want recur to have start only and to automatically set end date so there would be 10 occurrences of event.

Is it possible?

**Comment by c-trimm** [comment]
Sorry for the very late response - I haven't had time to work on this project for a very long time. In case you, or anyone, still cares. You could do this:

`dates = moment().recur().every([10]).daysOfMonth().every("monday").dayOfWeek().next(10);`
