### ISSUE TITLE
Is anyone actively monitoring this repo?

### ISSUE THREAD

**Issue by CorasApps** [c-trimm/moment-recur#66]
I find this to be a very versatile and useful moment plugin. I see Issues and PRs that have been lingering without resolution. 

For those who have the ability to merge... are you still active here? 

For others, have you found an alternative that meets your date recurrence needs?

**Comment by c-trimm** [comment]
I'm still around - just haven't had a lot of time to review/merge things. Some PRs are outstanding because the author hasn't updated their commits per request. If you would like to make contributions, please do so. I will try to find some time to review/merge. Thanks for your interest in my plugin!

**Comment by CorasApps** [comment]
Good to know. Thanks.
