### ISSUE TITLE
Non-ISO format used in NPM download

### ISSUE THREAD

**Issue by timemachine3030** [c-trimm/moment-recur#71]
The version downloaded from NPM uses a non-ISO date (YYYY/MM/DD) at
https://github.com/c-trimm/moment-recur/blob/master/moment-recur.js#L737

This causes the moment warning: "Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments"

`master` has the correct format of YYYY-MM-DD.

**Comment by c-trimm** [comment]
I've published the latest version to NPM, so this should now be fixed. Thanks!

**Comment by lordrepha1980** [comment]
This bug is back :(
