### ISSUE TITLE
Every 2nd friday?

### ISSUE THREAD

**Issue by JensWinter** [c-trimm/moment-recur#72]
How do I generate a rule the returns every 2nd fridays?

```
moment("2017-05-01").recur("2017-05-31").every("friday").daysOfWeek().every(2).weeks();
```

produces no dates. Shouldn't it return May 5th and May 19th?

**Comment by c-trimm** [comment]
I apologize for the late response. In case you still need to know:

This won't work as expected. the rule "every 2 weeks" will match every 2 weeks *from the start date* - 2017-05-01.

As a potential solution, you might try setting the start date as the first Friday of the month and then setting the "every 2 weeks" rule - but leave out the "every friday" rule.
