### ISSUE TITLE
use with angular 2

### ISSUE THREAD

**Issue by shaolinshaosson** [c-trimm/moment-recur#77]
Hi.
How can I install this in an angular2 app ?
I got momentjs working ( import * as moment from 'moment' ) but when I'm trying to import moment-recur (import 'moment-recur') I just get the error: Property 'recur' does not exist on type 'typeof moment'.
I installed both moment and moment-recur with npm.

**Comment by jefbarn** [comment]
Assuming typescript, you need a moment-recur.d.ts
Here's mine:
```
import { Moment, MomentInput } from 'moment'

declare module 'moment' {

  interface MomentRecurrence {
    (start: MomentInput, end: MomentInput): MomentRecurrence
    every (interval: number | (string | number)[], intervalType?: string): MomentRecurrence
    fromDate (from: MomentInput): MomentRecurrence
    all (format: string): string[]

    day (): MomentRecurrence
    days (): MomentRecurrence
    week (): MomentRecurrence
    weeks (): MomentRecurrence
    month (): MomentRecurrence
    months (): MomentRecurrence
    year (): MomentRecurrence
    years (): MomentRecurrence

    dayOfWeek (): MomentRecurrence
    daysOfWeek (): MomentRecurrence
    dayOfMonth (): MomentRecurrence
    daysOfMonth (): MomentRecurrence
    weekOfMonth (): MomentRecurrence
    weeksOfMonth (): MomentRecurrence
    weekOfYear (): MomentRecurrence
    weeksOfYear (): MomentRecurrence
    monthOfYear (): MomentRecurrence
    monthsOfYear (): MomentRecurrence
    weeksOfMonthByDay (): MomentRecurrence
  }

  interface Moment {
    recur (start: MomentInput, end: MomentInput): MomentRecurrence
  }

  const recur: MomentRecurrence
}
```

**Comment by shaolinshaosson** [comment]
Thank you, still strugling with trying to get it working  :(
Should I place that file in "node_modules/moment_recur"?
And how should I type the import ?

**Comment by jefbarn** [comment]
Put the file somewhere in your src directory (i.e. somewhere that your tsconfig will compile, I have a src/types folder I put all this stuff in), and just 
`import 'moment-recur'`

**Comment by shaolinshaosson** [comment]
Much obliged @jefbarn, worked perfectly!

**Comment by dessalines** [comment]
This should be reopened, and these typings added to the project.

**Comment by jefbarn** [comment]
@dessalines This project is not being maintained, you can check out my moment-recur-ts fork for complete typescript support.
