### ISSUE TITLE
Add new release that includes all()

### ISSUE THREAD

**Issue by joshuajabbour** [c-trimm/moment-recur#8]
v1.0.0 doesn't include the all method. Can you bump the version?

**Comment by bramski** [comment]
This repository seems to be defunct but this plugin is very useful.  Since @c-trimm has not touched it in 6 months I have made some updates and moved it to: https://github.com/bramski/moment-recur-js

Please revisit your issue there, thanks!

**Comment by bramski** [comment]
See: https://github.com/c-trimm/moment-recur/releases/tag/v1.0.1

I think this should include all().  But I'm not sure.  It's a cut from master so I believe it should be included.

**Comment by c-trimm** [comment]
Yes, it was added a while back, so the latest snapshot of master will contain it.
