### ISSUE TITLE
possible to get dates on monday or tuesdey every two weeks?

### ISSUE THREAD

**Issue by malleg** [c-trimm/moment-recur#9]
Is it possible with recur to get for e.g. dates on monday and tuesday every two weeks?

thanks for your help and this nice plugin for moments!

**Comment by bramski** [comment]
This repository seems to be defunct but this plugin is very useful.  Since @c-trimm has not touched it in 6 months I have made some updates and moved it to: https://github.com/bramski/moment-recur-js

Please revisit your issue there, thanks!

**Comment by c-trimm** [comment]
No, length intervals (such as every two weeks) use a start date. So, since today is Friday, every two weeks would match every other Friday. Length rules do not combine with the calendar rules.
